try {
  throw "oh no";
} catch (e) {
  console.log('Oh well');
  console.log(e)
}